spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: true
    mode: HTML
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
